/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ToonMat } from "./mats/ToonMat";
import { MeshBasicMaterial } from "three";

export default function Bush(props) {
  const { nodes, materials } = useGLTF("models/bush.glb");
  return (
    <group {...props} dispose={null} rotation={[-.2, 0, 0]} position={ [3.5, 0, 0] } scale={[.3, .5, .5]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        //material={materials.Material}
      >
        <ToonMat color="#2E7516" />
        {/* <meshBasicMaterial  color={ 0x2E7516 } /> */}
      </mesh>
    </group> 
  );
}

useGLTF.preload("models/bush.glb");