/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("../models/car-4.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[0, 0, -Math.PI / 2]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["356C_Porsche356_0"].geometry}
                    material={materials.Porsche356}
                  />
                </group>
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[0, 0, -Math.PI / 2]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.chrome_Porsche356_0019.geometry}
                    material={materials.Porsche356}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Hubcap.geometry}
                    material={materials.Porsche356}
                  />
                </group>
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[0, 0, -Math.PI / 2]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.blinkers.geometry}
                    material={materials.Porsche356}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.headlights.geometry}
                    material={materials.glass}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.tailLights.geometry}
                    material={materials.Porsche356}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.windows.geometry}
                    material={materials.glass}
                  />
                </group>
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[0, 0, -Math.PI / 2]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.interior_Porsche356_0.geometry}
                    material={materials.Porsche356}
                  />
                </group>
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[0, 0, -Math.PI / 2]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rubber_Porsche356_0.geometry}
                    material={materials.Porsche356}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../models/car-4.glb");
